### PR TITLE
Add torrent-file and torrent-info resolvers

### PR DESCRIPTION
**Pull request by BubuAnabelas**
I took [ipld-ethereum](https://github.com/ipld/js-ipld-ethereum)'s code and modify it to complement with the `parse-torrent` and `bencode` packages to adapt it to implement the [IPLD Interface](https://github.com/ipld/interface-ipld-format).

I think this implementation is pretty much complete, it has both torrent-file and torrent-info resolvers. It also has some test cases to check it working fine, but I'm sure there are lots of other things that can be tested out to be sure it works as intended.

This is related to https://github.com/ipfs/js-ipfs/issues/779 and maybe it will help to implement the `ipfs-torrent` service.

### CODE REVIEW

**Comment by rvagg** [comment]
I'm suspecting that @mikeal might be the best person to review this, I'm not as schooled in torrent formats. My initial question though is regarding the CID:Binary mapping which is critical for IPLD and I believe might be a problem for torrents. In your implementation, do you have a clear mapping of CID to whatever is decoded? Could I encode from the data you're instantiating back into binary form and generate the same CID from that data or are there additional bits of information missing, _or_ added that break the "this raw data is all hashed and prefixed with multihash+codec+etc to produce a CID" contract of IPLD?

**Comment by BubuAnabelas** [comment]
@rvagg In the case of torrent-info, CIDs are produced by hashing the binary representation of the [*info dictionary*](https://www.bittorrent.org/beps/bep_0003.html#info-dictionary), the same way info-hashes are calculated. In this implementation I just considered BEP3's definition because [BitTorrent v2 (BEP52)](https://www.bittorrent.org/beps/bep_0052.html) isn't really implemented anywhere afaik (it's been added to [libtorrent](https://github.com/arvidn/libtorrent/pull/3873) but hasn't shipped yet).

For torrent-files it's a little different, since they just add metainfo to the torrent-info, there can be many different torrent files for the same torrent. For example, by adding a tracker to the [announce-list](https://www.bittorrent.org/beps/bep_0012.html) would change a torrent-file CID, but the torrent-info would remain the same.

Given that both torrent-info and torrent-file are bencoded data, there's an unique mapping between CID and torrent-info/torrent-data. Both resolvers have a test case for this in the code I have submitted.

**Comment by BubuAnabelas** [comment]
A long time has passed since I've made this PR, I don't even remember if there where any caveat why this wouldn't work, yet it hasn't been merged.

I just wanted to mention a project built on top of IPFS which could take advantage of this IPLD interface with some modifications.
> [gigacat](https://github.com/etagate/gigacat) is a standalone web application designed to use IPFS peer-to-peer network to retrieve torrent dumps, formatted as CSV files, and to build a local database from the dump, letting the user search through it using text search.

Also, [BitTorrent v2 was added to libtorrent](https://blog.libtorrent.org/2020/09/bittorrent-v2/) and [some clients](https://github.com/qbittorrent/qBittorrent/issues/15109) are already testing it.

I will leave this PR open so it can be merged if it's find useful in the future.

**Comment by vmx** [comment]
In case someone wants to pick up this work, I'd like to mention that IPLD Codecs now have a new interface. IPFS is now using https://github.com/multiformats/js-multiformats#ipld-codecs-multicodec for IPLD things.

**Comment by rvagg** [comment]
closed for archival

**Pull request closed without merging**
