### PR TITLE
[WIP] feat/v0.1.0

### PR DESCRIPTION
**Pull request by daviddias**

### CODE REVIEW

**Comment by danimesq** [comment]
@daviddias
Label says ready, but title yet is [WIP]

**Comment by daviddias** [comment]
@DaniellMesquita this is waaay old code :) The `ready` label is a leftover from Waffle.io (Kanban), where `ready` was equivalent to `backlog`. The PR is still not _ready_.

**Comment by danimesq** [comment]
Why not prioritizing torrent in IPLD? Which one is more important than that?

**Comment by danimesq** [comment]
@daviddias

I'm projecting oTorrent app (formly omniTorrent), which would download the same file both from IPFS and from bitorrent, and also seeding both.
You really think torrent isn't the priority for IPLD? And I don't talk about piracy; Ubuntu ISO is a example of how torrents are useful.

**Comment by daviddias** [comment]
@DaniellMesquita I absolutely believe that Torrents are important for IPLD. [It is what IPLD is designed for, to create a way in which any kind of hash linked graphs can interop and through that, create a unifying language to resolve and query that data.](https://github.com/ipfs/js-ipfs/tree/master/examples/traverse-ipld-graphs#resolve-through-ipld-graphs-with-the-dag-api)

Previous work was:

- Support for Ethereum graphs https://github.com/ipfs/js-ipfs/tree/master/examples/explore-ethereum-blockchain && https://github.com/ipfs/js-ipfs/issues/763
- Support for git graphs https://github.com/ipfs-shipyard/IGiS
- Unixfs itself is a specialized IPLD Graph.

You can track the progress of adding Torrent support at https://github.com/ipfs/js-ipfs/issues/779 and it seams that the IPLD team intends to ship it soon (i.e. perhaps Q4) https://github.com/ipfs/js-ipfs/issues/1893

**Comment by rvagg** [comment]
closing for archival

**Pull request closed without merging**
